/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * staff.java
 *
 * Created on Mar 18, 2010, 11:25:22 AM
 */

/**
 *
 * @author Admin2
 */

import com.lindo.Lingd20;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class staff extends javax.swing.JDialog {
   DefaultTableModel tabla = new DefaultTableModel();

   // Load the Lingo JNI interface
   static {
      System.loadLibrary( "Lingj64_20");
   }

   // Create a new Lingo object, which we will use to interface with Lingo
   Lingd20 lng = new Lingd20();

   // Stores the Lingo JNI environment pointer
   Object pLngEnv;

   int nLastIterationCount;

   /** Creates new form staff */
   public staff(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
       initComponents();
       jCapacidad1_1.setText("22758");
       jCapacidad1_2.setText("6575");
       jCapacidad1_3.setText("4046");
       jCapacidad1_4.setText("6069");
       jCapacidad1_5.setText("11126");
       jCapacidad2_1.setText("3767");
       jCapacidad2_2.setText("1088");
       jCapacidad2_3.setText("670");
       jCapacidad2_4.setText("1004");
       jCapacidad2_5.setText("1841");
       // Create the Lingo environment.
       // We do this here in the constructor so as not to repeat this
       // for each subsequent solve, improving performance.
       // Be sure to delete the Lingo environment on exit.
       pLngEnv = lng.LScreateEnvLng();
       if ( pLngEnv == null)
       {
          JOptionPane.showMessageDialog(null, "Unable to create Lingo environment");
          return;
       }
   }

   public void Tabla(){
        String[] titulo = new String[]{"Sku's","Plantas","Almacenes","Semana 1","Semana 2","Semana 3","Semana 4"
                ,"Semana 5","Semana 6","Semana 7","Semana 8","Semana 9","Semana 10","Semana 11","Semana 12"};
        tabla.setColumnIdentifiers(titulo);
        jTabla.setModel(tabla);
    };

    public void Agregar(double[] dX) {
        tabla.setRowCount(0);
        String[] skus = {"Sku 1", "Sku 2"};
        String[] plantas = {"Huachipa", "Arequipa", "Majes", "Cajamarca", "Trujillo"};
        String[] almacenes = {"Lima", "Piura", "Cajamarca", "Chiclayo", "Trujillo", "Tarapoto", "Huancayo", "Ica", "Arequipa", "Cuzco", "Juliaca", "Tacna"};
        
        String seleccionadoSku = cbSku.getSelectedItem().toString();
        String seleccionadoPlanta = cbPlanta.getSelectedItem().toString();
        String seleccionadoAlmacen = cbAlmacen.getSelectedItem().toString();
        
        int i=0;
        for (String sku : skus) {
            for (String planta : plantas) {
                for (String almacen : almacenes) {
                    boolean agregarFila = true;

                    if (!seleccionadoSku.equals("[Escoger]") && !sku.equals(seleccionadoSku)) {
                        agregarFila = false;
                    }

                    if (!seleccionadoPlanta.equals("[Escoger]") && !planta.equals(seleccionadoPlanta)) {
                        agregarFila = false;
                    }

                    if (!seleccionadoAlmacen.equals("[Escoger]") && !almacen.equals(seleccionadoAlmacen)) {
                        agregarFila = false;
                    }
                    if (agregarFila) {
                        tabla.addRow(new Object[]{sku, planta, almacen,dX[i],dX[i+1],dX[i+2],dX[i+3],dX[i+4],dX[i+5],dX[i+6],dX[i+7],dX[i+8],dX[i+9],dX[i+10],dX[i+11]});
                        i=i+12;
                    } else {
                        i += 12;  // Incrementar i incluso si la fila no se agrega
                    }

                }
            }
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCapacidad1_1 = new javax.swing.JTextField();
        jButtonSolve = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jCapacidad1_2 = new javax.swing.JTextField();
        jCapacidad1_3 = new javax.swing.JTextField();
        jCapacidad1_4 = new javax.swing.JTextField();
        jCapacidad1_5 = new javax.swing.JTextField();
        jCapacidad2_1 = new javax.swing.JTextField();
        jCapacidad2_2 = new javax.swing.JTextField();
        jCapacidad2_5 = new javax.swing.JTextField();
        jCapacidad2_3 = new javax.swing.JTextField();
        jCapacidad2_4 = new javax.swing.JTextField();
        cbSku = new javax.swing.JComboBox<>();
        cbPlanta = new javax.swing.JComboBox<>();
        cbAlmacen = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lingo Staff Scheduling using Java");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                staff.this.windowClosing(evt);
            }
        });

        jCapacidad1_1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jCapacidad1_1.setText("0");
        jCapacidad1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacidad1_1ActionPerformed(evt);
            }
        });

        jButtonSolve.setText("Solve");
        jButtonSolve.setActionCommand("jButton1");
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolveActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Sku 1");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Sku 2");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Huachipa");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Arequipa");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Majes");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Cajamarca");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Capacidad Total");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Trujillo");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("PLANTAS");

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTabla);

        jCapacidad1_2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jCapacidad1_2.setText("0");
        jCapacidad1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacidad1_2ActionPerformed(evt);
            }
        });

        jCapacidad1_3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jCapacidad1_3.setText("0");
        jCapacidad1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacidad1_3ActionPerformed(evt);
            }
        });

        jCapacidad1_4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jCapacidad1_4.setText("0");
        jCapacidad1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacidad1_4ActionPerformed(evt);
            }
        });

        jCapacidad1_5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jCapacidad1_5.setText("0");
        jCapacidad1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacidad1_5ActionPerformed(evt);
            }
        });

        jCapacidad2_1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jCapacidad2_1.setText("0");
        jCapacidad2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacidad2_1ActionPerformed(evt);
            }
        });

        jCapacidad2_2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jCapacidad2_2.setText("0");
        jCapacidad2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacidad2_2ActionPerformed(evt);
            }
        });

        jCapacidad2_5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jCapacidad2_5.setText("0");
        jCapacidad2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacidad2_5ActionPerformed(evt);
            }
        });

        jCapacidad2_3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jCapacidad2_3.setText("0");
        jCapacidad2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacidad2_3ActionPerformed(evt);
            }
        });

        jCapacidad2_4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jCapacidad2_4.setText("0");
        jCapacidad2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacidad2_4ActionPerformed(evt);
            }
        });

        cbSku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Escoger]", "Sku 1", "Sku 2" }));

        cbPlanta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Escoger]", "Huachipa", "Arequipa", "Majes", "Cajamarca", "Trujillo" }));

        cbAlmacen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Escoger]", "Lima", "Piura", "Cajamarca", "Chiclayo", "Trujillo", "Tarapoto", "Huancayo", "Ica", "Arequipa", "Cuzco", "Juliaca", "Tacna" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSolve)
                .addGap(18, 18, 18)
                .addComponent(jButtonExit)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCapacidad2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCapacidad2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCapacidad1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCapacidad1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCapacidad2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCapacidad2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCapacidad2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCapacidad1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCapacidad1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCapacidad1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel19)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel20)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel21)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel31)
                        .addGap(14, 14, 14)))
                .addGap(43, 43, 43)
                .addComponent(cbSku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSolve)
                            .addComponent(jButtonExit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCapacidad1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jCapacidad1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCapacidad1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCapacidad1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCapacidad1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbSku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jCapacidad2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCapacidad2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCapacidad2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCapacidad2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCapacidad2_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static int MySolverCallback( Object pnLng, int iLoc, Object jobj)
    {
       staff s = (staff) jobj;
       int nIterations[] = new int [1];
       s.lng.LSgetCallbackInfoIntLng( pnLng, Lingd20.LS_IINFO_ITERATIONS_LNG, nIterations);
       return( 0);
    }

    private static int MyErrorCallback( Object pnLng, int nErrorCode, String jsErrMessage, Object jobj)
    {
       JOptionPane.showMessageDialog(null,
        "Lingo error code: " + nErrorCode);
       JOptionPane.showMessageDialog(null,
        "Lingo error message:\n\n " + jsErrMessage);
       return( 0);
    }

    @SuppressWarnings("static-access")
    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed

       Double d=0.;
       String s;

       double dCapacidad[] = new double[10];
       double dDemanda[] = new double [288];     
       double dCosto[] = new double [60];
       double dX[] = new double [1440];
       double dStatus[] = new double [1];

       //StringBuffer sbDays = new StringBuffer( "MON \n TUE \n WED \n THU \n FRI \n SAT \n SUN");
       //StringBuffer sbDays2 = new StringBuffer( "                                                ");

       try
       {
          s = jCapacidad1_1.getText();   dCapacidad[0] = Double.valueOf( s);
          s = jCapacidad1_2.getText();   dCapacidad[1] = Double.valueOf( s);
          s = jCapacidad1_3.getText();   dCapacidad[2] = Double.valueOf( s);
          s = jCapacidad1_4.getText();   dCapacidad[3] = Double.valueOf( s);
          s = jCapacidad1_5.getText();   dCapacidad[4] = Double.valueOf( s);
          s = jCapacidad2_1.getText();   dCapacidad[5] = Double.valueOf( s);
          s = jCapacidad2_2.getText();   dCapacidad[6] = Double.valueOf( s);
          s = jCapacidad2_3.getText();   dCapacidad[7] = Double.valueOf( s);
          s = jCapacidad2_4.getText();   dCapacidad[8] = Double.valueOf( s);
          s = jCapacidad2_5.getText();   dCapacidad[9] = Double.valueOf( s);
       }
       catch ( Exception e)
       {
          JOptionPane.showMessageDialog(null, "Invalid staffing needs data.");
          return;
       }

       // open a log file
       int nErr = lng.LSopenLogFileLng( pLngEnv, "F:/LINGO64_20/Lingo64_20");
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
          JOptionPane.showMessageDialog(null, "LSopenLogFileLng() error: " + nErr);
          return;
       }

       // pass Lingo the name of the solver callback function...
       nErr = lng.LSsetCallbackSolverLng( pLngEnv, "MySolverCallback", this);
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
          JOptionPane.showMessageDialog(null, "LSsetCallbackSolverLng() error");
          return;
       }

       // ...and the error callback function
       nErr = lng.LSsetCallbackErrorLng( pLngEnv, "MyErrorCallback", this);
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
          JOptionPane.showMessageDialog(null, "LSsetCallbackErrorLng() error");
          return;
       }

       // pass lingo a pointer to the DAYS set     
       int[] nPointersNow = new int[1];
       
       // pass lingo a pointer to the staffing needs
       nErr = lng.LSsetPointerLng(pLngEnv, dCapacidad, nPointersNow);
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
           JOptionPane.showMessageDialog(null, "LSsetPointerLng() error");
           return;
       }

       // pass pointers to output areas
       nErr = lng.LSsetPointerLng(pLngEnv, dDemanda, nPointersNow);
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
          JOptionPane.showMessageDialog(null, "LSsetPointerLng() error");
          return;
       }

       nErr = lng.LSsetPointerLng(pLngEnv, dCosto, nPointersNow);
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
          JOptionPane.showMessageDialog(null, "LSsetPointerLng() error");
          return;
       }

       nErr = lng.LSsetPointerLng(pLngEnv, dX, nPointersNow);
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
          JOptionPane.showMessageDialog(null, "LSsetPointerLng() error");
          return;
       }

       nErr = lng.LSsetPointerLng( pLngEnv, dStatus, nPointersNow);
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
          JOptionPane.showMessageDialog(null, "LSsetPointerLng() error");
          return;
       }
      

       // construct the script
       // echo input to log file
       String sScript = "SET ECHOIN 1" + "\n";

       // load the model from disk
       sScript = sScript + "TAKE JStaffptr.lng" + "\n";

       // view the formulation
       sScript = sScript + "LOOK ALL" + "\n";

       // solve
       sScript = sScript + "GO" + "\n";

       // exit script processor
       sScript = sScript + "QUIT" + "\n";

       // run the script
       dStatus[0] = -1;
       nLastIterationCount = -1;
       nErr = lng.LSexecuteScriptLng( pLngEnv, sScript);
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
          System.out.println( "***LSexecuteScriptLng error***: " + nErr);
          return;
       }

       // clear the pointers to force update of local arrays
       // ***NOTE*** solution won't get passed to local arrays until
       // LSclearPointersLng is called!!!
       nErr = lng.LSclearPointersLng( pLngEnv);
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
          System.out.println( "***LSclearPointerLng() error***: " + nErr);
          return;
       }

       // check the solution status
       if ( dStatus[0] != lng.LS_STATUS_GLOBAL_LNG)
        System.out.println( "***Unable to Solve*** dStatus:" + dStatus[0]);

       // close Lingo's log file
       nErr = lng.LScloseLogFileLng( pLngEnv);
       if ( nErr != lng.LSERR_NO_ERROR_LNG )
       {
          System.out.println( "***LScloseLogFileLng() error***: " + nErr);
          return;
       }
        Tabla();
        Agregar(dX);
       // dsiplay the solution
       //Integer nTotal = 0;
       Integer n;
   
    }//GEN-LAST:event_jButtonSolveActionPerformed

    @SuppressWarnings("static-access")
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
       // delete the Lingo environment
       lng.LSdeleteEnvLng( pLngEnv);
       System.exit( 0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    @SuppressWarnings("static-access")
    private void windowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosing
       // delete the Lingo environment
       lng.LSdeleteEnvLng( pLngEnv);
    }//GEN-LAST:event_windowClosing

    private void jCapacidad1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacidad1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacidad1_1ActionPerformed

    private void jCapacidad1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacidad1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacidad1_2ActionPerformed

    private void jCapacidad1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacidad1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacidad1_3ActionPerformed

    private void jCapacidad1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacidad1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacidad1_4ActionPerformed

    private void jCapacidad1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacidad1_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacidad1_5ActionPerformed

    private void jCapacidad2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacidad2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacidad2_1ActionPerformed

    private void jCapacidad2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacidad2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacidad2_2ActionPerformed

    private void jCapacidad2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacidad2_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacidad2_5ActionPerformed

    private void jCapacidad2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacidad2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacidad2_3ActionPerformed

    private void jCapacidad2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacidad2_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacidad2_4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                staff dialog = new staff(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAlmacen;
    private javax.swing.JComboBox<String> cbPlanta;
    private javax.swing.JComboBox<String> cbSku;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JTextField jCapacidad1_1;
    private javax.swing.JTextField jCapacidad1_2;
    private javax.swing.JTextField jCapacidad1_3;
    private javax.swing.JTextField jCapacidad1_4;
    private javax.swing.JTextField jCapacidad1_5;
    private javax.swing.JTextField jCapacidad2_1;
    private javax.swing.JTextField jCapacidad2_2;
    private javax.swing.JTextField jCapacidad2_3;
    private javax.swing.JTextField jCapacidad2_4;
    private javax.swing.JTextField jCapacidad2_5;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabla;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
